language: python
python:
  - "3.4"
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests
env:
  - TESTMODE=full
    COVERAGE=--coverage
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - sudo cp /usr/lib/x86_64-linux-gnu/libm.so /usr/lib/x86_64-linux-gnu/libm.so.6
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - deps='pip numpy>=1.8 scipy>=0.13 nose shapely h5py cython scikit-image pep8 flake8 scikit-learn sphinx numpydoc pillow future'
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then conda install -c https://conda.binstar.org/anaconda opencv; fi
  - pip install sphinxcontrib-napoleon picos
  - if [ "${TESTMODE}" == "full" ]; then pip install coverage coveralls; fi
  - python -V
  - echo $PATH
  - cp /usr/lib/x86_64-linux-gnu/libm.so /home/travis/miniconda/envs/test-environment/bin/../lib/libm.so.6
  - ldconfig -p
script: 
    - flake8 *.py sima --exclude sima/misc/tifffile.py,sima/__init__.py,test*.py,sima/misc/align.py,sima/motion/__init__.py,sima/segment/__init__.py
    - python runtests.py --doctests -m $TESTMODE $COVERAGE
    - cd doc && make html && cd ..
branches:
  only:
    - master
    - 0.3.x
    - 1.0.x
    - 1.1.x
after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      if [ "${TESTMODE}" == "full" ]; then cp build/test/.coverage . && coveralls; fi; fi
